"""
neuroagent.py — NeuroAgent Decision Engine
===========================================

Reads the Evidence Fusion output and makes the
final decision for each ICA component.

Possible decisions:

    KEEP
    REMOVE
    REVIEW

Evidence used:

    ICLabel
    PSD
    ALICE
    Fusion artifact score
    Fusion brain score
"""

from pathlib import Path

import pandas as pd


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[1]

PROCESSED_DIR = BASE_DIR / "data" / "processed"

FUSION_FILE = PROCESSED_DIR / "S002R01_fusion.csv"

OUTPUT_FILE = PROCESSED_DIR / "S002R01_neuroagent.csv"


# ============================================================
# LOAD FUSION DATA
# ============================================================

def load_fusion_results():

    print("\n==========================================")
    print("          NEUROAGENT")
    print("       DECISION ENGINE")
    print("==========================================")

    print("\nLoading evidence fusion results:")
    print(FUSION_FILE)

    if not FUSION_FILE.exists():
        raise FileNotFoundError(
            f"\nFusion file not found:\n{FUSION_FILE}"
        )

    df = pd.read_csv(FUSION_FILE)

    print("\nFusion results loaded successfully.")

    print("\n==========================================")
    print("DATA INFORMATION")
    print("==========================================")

    print(f"Components : {len(df)}")
    print(f"Columns    : {len(df.columns)}")

    print("\nAvailable columns:")

    for column in df.columns:
        print(f"  - {column}")

    return df


# ============================================================
# NEUROAGENT REASONING
# ============================================================

def decide_component(row):

    """
    Analyze one ICA component using the evidence
    generated by ICLabel, PSD, ALICE and fusion.
    """

    # --------------------------------------------------------
    # Read actual columns from fusion.csv
    # --------------------------------------------------------

    component = row["component"]

    iclabel_label = str(
        row["iclabel_label"]
    ).lower()

    iclabel_confidence = float(
        row["iclabel_confidence"]
    )

    iclabel_artifact_score = float(
        row["iclabel_artifact_score"]
    )

    psd_artifact_score = float(
        row["psd_artifact_score"]
    )

    alice_artifact_score = float(
        row["alice_artifact_score"]
    )

    artifact_score = float(
        row["artifact_score"]
    )

    brain_score = float(
        row["brain_score"]
    )

    fusion_decision = str(
        row["decision"]
    ).upper()

    # ========================================================
    # EVIDENCE ANALYSIS
    # ========================================================

    artifact_votes = 0
    brain_votes = 0

    # --------------------------------------------------------
    # ICLabel
    # --------------------------------------------------------

    artifact_labels = [
        "eye blink",
        "muscle artifact",
        "channel noise",
        "heart beat",
        "line noise"
    ]

    if any(
        artifact in iclabel_label
        for artifact in artifact_labels
    ):

        if iclabel_confidence >= 0.70:
            artifact_votes += 1

    elif "brain" in iclabel_label:

        if iclabel_confidence >= 0.70:
            brain_votes += 1

    # --------------------------------------------------------
    # PSD
    # --------------------------------------------------------

    if psd_artifact_score >= 0.70:

        artifact_votes += 1

    elif psd_artifact_score <= 0.30:

        brain_votes += 1

    # --------------------------------------------------------
    # ALICE
    # --------------------------------------------------------

    if alice_artifact_score >= 0.70:

        artifact_votes += 1

    elif alice_artifact_score <= 0.30:

        brain_votes += 1

    # --------------------------------------------------------
    # Overall Fusion Score
    # --------------------------------------------------------

    if artifact_score >= 0.70:

        artifact_votes += 1

    elif artifact_score <= 0.30:

        brain_votes += 1

    # ========================================================
    # NEUROAGENT DECISION
    # ========================================================

    # Strong multi-source artifact evidence
    if artifact_votes >= 2:

        decision = "REMOVE"

        reason = (
            f"Multiple evidence sources indicate artifact. "
            f"ICLabel={iclabel_label} "
            f"({iclabel_confidence:.2%}), "
            f"artifact_score={artifact_score:.2f}."
        )

    # Strong multi-source brain evidence
    elif brain_votes >= 2:

        decision = "KEEP"

        reason = (
            f"Multiple evidence sources indicate "
            f"brain-related activity. "
            f"ICLabel={iclabel_label} "
            f"({iclabel_confidence:.2%}), "
            f"brain_score={brain_score:.2f}."
        )

    # Strong fusion decision
    elif fusion_decision == "REMOVE" and artifact_score >= 0.60:

        decision = "REMOVE"

        reason = (
            "Evidence fusion indicates probable artifact."
        )

    elif fusion_decision == "KEEP" and brain_score >= 0.60:

        decision = "KEEP"

        reason = (
            "Evidence fusion indicates probable "
            "brain-related activity."
        )

    # Conflicting evidence
    else:

        decision = "REVIEW"

        reason = (
            "Evidence is ambiguous or conflicting. "
            "Component requires further review."
        )

    return decision, reason


# ============================================================
# RUN NEUROAGENT
# ============================================================

def run_neuroagent(df):

    print("\n==========================================")
    print("       NEUROAGENT REASONING")
    print("==========================================")

    print("\nAnalyzing ICA components...")

    decisions = []
    reasons = []

    for _, row in df.iterrows():

        decision, reason = decide_component(row)

        decisions.append(decision)
        reasons.append(reason)

    df = df.copy()

    df["neuroagent_decision"] = decisions

    df["neuroagent_reason"] = reasons

    return df


# ============================================================
# DISPLAY RESULTS
# ============================================================

def display_results(df):

    print("\n==========================================")
    print("      NEUROAGENT FINAL DECISIONS")
    print("==========================================")

    display_columns = [
        "component",
        "iclabel_label",
        "iclabel_confidence",
        "artifact_score",
        "brain_score",
        "decision",
        "neuroagent_decision"
    ]

    print("\nFirst 15 components:\n")

    print(
        df[display_columns]
        .head(15)
        .to_string(index=False)
    )

    # --------------------------------------------------------
    # Distribution
    # --------------------------------------------------------

    print("\n==========================================")
    print("   FINAL DECISION DISTRIBUTION")
    print("==========================================")

    print(
        df["neuroagent_decision"]
        .value_counts()
        .to_string()
    )


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(df):

    PROCESSED_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print("\n==========================================")
    print("    NEUROAGENT RESULTS SAVED")
    print("==========================================")

    print("\nFile:")
    print(OUTPUT_FILE)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # 1. Load evidence
    # --------------------------------------------------------

    df = load_fusion_results()

    # --------------------------------------------------------
    # 2. NeuroAgent reasoning
    # --------------------------------------------------------

    df = run_neuroagent(df)

    # --------------------------------------------------------
    # 3. Display results
    # --------------------------------------------------------

    display_results(df)

    # --------------------------------------------------------
    # 4. Save
    # --------------------------------------------------------

    save_results(df)

    print("\n==========================================")
    print("     NEUROAGENT STAGE COMPLETE")
    print("==========================================")

    print("\nNext stage →")

    print("EEG RECONSTRUCTION")
    print("       ↓")
    print("Remove selected ICA components")
    print("       ↓")
    print("Reconstruct CLEAN EEG")